language: java
  
jdk:
  - oraclejdk8
  
# If your build needs more advanced behavior, see detailed Travis CI instructions:
# https://docs.travis-ci.com/user/languages/java/

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
